Fixed update skip feature

diff --git a/update b/update
--- a/update
+++ b/update
@@ -37,28 +37,27 @@ function update {
 
 # Original code by Dennis Simpson
 # Modified by Kyle Warwick-Mathieu
-if [ "$1" != "-s" ]; then # If there is no -s argument then run the updater
-	echo "Checking if script is up to date, please wait"
-	wget -nv -O $UPDATE_FILE $UPDATE_BASE >& /dev/null # This will silently download the file
-	if [ $? != "0" ] ; then
-		curl "$UPDATE_BASE" -o "$UPDATE_FILE" >& /dev/null
-	fi
-	diff $0 $UPDATE_FILE >& /dev/null # This will compare the current file you're running against the newly downloaded file
-	if [ "$?" != "0" -a -s $UPDATE_FILE ]; then # If the exit code is not 0 (in other words if the file is different)
-		mv $UPDATE_FILE $0 # Rename update file to the script you're running
-		chmod +x $0 # Change the mode on the newly renamed file
-		echo "$0 updated"
-		$0 -s # Runs the script with the -s argument to prevent an endless loop
-		exit
-	else
-		rm $UPDATE_FILE # If no updates are available, simply remove the file
-	fi
+echo "Checking if script is up to date, please wait"
+wget -nv -O $UPDATE_FILE $UPDATE_BASE >& /dev/null # This will silently download the file
+if [ $? != "0" ] ; then
+	curl "$UPDATE_BASE" -o "$UPDATE_FILE" >& /dev/null
+fi
+diff $0 $UPDATE_FILE >& /dev/null # This will compare the current file you're running against the newly downloaded file
+if [ "$?" != "0" -a -s $UPDATE_FILE ]; then # If the exit code is not 0 (in other words if the file is different)
+	mv $UPDATE_FILE $0 # Rename update file to the script you're running
+	chmod +x $0 # Change the mode on the newly renamed file
+	echo "$0 updated"
+	$0 -s # Runs the script with the -s argument to prevent an endless loop
+	exit
+else
+	rm $UPDATE_FILE # If no updates are available, simply remove the file
 fi
 }
 
 # Now we have to call the update function
 
 update_init
-update # This will call our update function
-
+if [ "$1" != "-s" ]; then # If there is no -s argument then run the updater
+	update # This will call our update function
+fi
 echo "Hello! I'm version $VER of the script!"
